[package]
name = "rulox"
version = "0.1.0"
edition = "2021"
default-run = "rulox"
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[[bin]]
name = "gen_ast"

[dependencies]
