# expression ::= literal
#                 | unary
#                 | binary
#                 | grouping ;

expression ::= equality ;
## each rule only matches the expressions at it's precedence level or higher
equality ::= comparison ( ( "!=" | "==" ) comparison )*
comparison ::= term ( ( ">" | ">=" | "<" | "<=" ) term )*
term ::= factor ( ( "-" | "+" ) factor )*
factor ::= unary ( ( "/" | "*" ) unary )* ;
unary ::= ( "!" | "-" ) unary | primary ;
primary ::= NUMBER | STRING | "true" | "false" | "nil" | "(" expression ")" ;

literal ::= NUMBER | STRING | "true" | "false" | "nil" ;
grouping ::= "(" expression ")" ;
unary ::= ("-" | "!") expression ;
binary ::= expression operator expression ;
operator = "==" | "!=" | "<" | "<=" | ">" | ">=" 
            | "+" | "-" | "*" | "/" ;